### ISSUE TITLE
csnr-devops-lab

### ISSUE THREAD

**Issue by agehlers** [BCDevOps/innovation-lab-projects#1]
``` 
name: CSNR DevOps LAB
description: CSNR DevOps LAB Project Space
team:
 - name: Clecio Varjao
   github-handle: cvarjao
   role: DevOps Specialist, Lead
repository: 
environments:
 - name: TOOLS
   url: https://jenkins.csnr-devops-lab-tools.pathfinder.gov.bc.ca/
 - name: DEPLOY
   url: https://*.csnr-devops-lab-deploy.pathfinder.gov.bc.ca/
```
