### ISSUE TITLE
ag-devops-lab

### ISSUE THREAD

**Issue by agehlers** [BCDevOps/innovation-lab-projects#2]
```
name: AG DevOps LAB
description: AG DevOps LAB Project Space
team:
 - name: Ryan Loisell
   github-handle: rloisell
   role: Solutions Architect, Lead
repository: 
environments:
 - name: TOOLS
   url: https://jenkins.ag-devops-lab-tools.pathfinder.gov.bc.ca/
 - name: DEPLOY
   url: https://*.ag-devops-lab-deploy.pathfinder.gov.bc.ca/
```
