### ISSUE TITLE
agri-nmp

### ISSUE THREAD

**Issue by agehlers** [BCDevOps/innovation-lab-projects#3]
```
name: agri-nmp
description: Ministry of Agriculture Nutrition Management Program
product: nmp
team-name: agri
team:
 - name: Gary Wong
   github-handle: garywong-bc
   role: 
   name: Clecio Varjao
   GitHub-handle: cvarjao
   role: DevOps Specialist, Lead
repository: https://github.com/bcgov/agri-nmp.git
environments:
 - name: TOOLS
   url: https://jenkins-agri-nmp-tools.pathfinder.gov.bc.ca/
   url: https://sonarqube-agri-nmp-tools.pathfinder.gov.bc.ca/
 - name: DEV
   url: https://agri-nmp-dev.pathfinder.gov.bc.ca/
   url: https://nmp2-agri-nmp-dev.pathfinder.gov.bc.ca/
 - name: TEST
   url: https://agri-nmp-test.pathfinder.gov.bc.ca/
 - name: PROD
   url: https://agri-nmp-prod.pathfinder.gov.bc.ca/
```
